### ISSUE TITLE
One Error of "make evnn_pytorch"

### ISSUE THREAD

**Issue by gary23ai** [KhaleelKhan/EvNN#3]
![image](https://github.com/Efficient-Scalable-Machine-Learning/EvNN/assets/28098248/ea807f76-740e-4989-81d2-db353ecefb21)

**Comment by KhaleelKhan** [comment]
Could you please provide more details such as the CUDA toolkit version and the GPU compute capability you are using?
Earlier versions of CUDA arch don't support half ops, but the directive at inline_ops.h(120) should take care of this.
`#if defined(__CUDA_ARCH__) && (__CUDA_ARCH__ >= 600)`

**Comment by gary23ai** [comment]
![image](https://github.com/Efficient-Scalable-Machine-Learning/EvNN/assets/28098248/5200c679-b324-469f-89b0-6cff05616fdd)

**Comment by gary23ai** [comment]
The above issues were resolved by upgrading to CUDA 11.

**Comment by KhaleelKhan** [comment]
Thank you for raising this issue.
CUDA toolkit v 10.1 doesn't have __habs operation (See: [cuda 10.1](https://docs.nvidia.com/cuda/archive/10.1/cuda-math-api/group__CUDA__MATH____HALF__FUNCTIONS.html#group__CUDA__MATH____HALF__FUNCTIONS))

Can you please try using v10.2+
