### ISSUE TITLE
Compilation with CUDA 12

### ISSUE THREAD

**Issue by pascalkuthe** [KhaleelKhan/EvNN#6]
The Makefile in this repo fails if compiling with CUDA12.

The issue is that the `GPU_ARCH_FLAGS` are hardcoded and include `-gencode arch=compute_37,code=compute_37` The compute_37 architecture is not supported anymore in CUDA 12. Simply removing these flags from the makefile fixes the compilation. 

That would break compatibility with older Tesla K80 cards. Ideally, instead of hardcoding the architectures, there would be a way to configure the architecture yourself based on the GPU/CUDA version you use.

**Comment by KhaleelKhan** [comment]
Fixed in #10
