### ISSUE TITLE
undefined symbol: _Z11cblas_sgemm11CBLAS_ORDER15CBLAS_TRANSPOSES0_iiifPKfiS2_ifPfi

### ISSUE THREAD

**Issue by YuehaoHuang** [KhaleelKhan/EvNN#7]
It reported an error that "undefined symbol: _Z11cblas_sgemm11CBLAS_ORDER15CBLAS_TRANSPOSES0_iiifPKfiS2_ifPfi"
When I run "import evnn_pytorch as evnn"

**Comment by KhaleelKhan** [comment]
demangled name of the undefined function is `cblas_sgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, int, float const*, int, float, float*, int)`

This means the cblas library is missing or not on the path. Try to find the path where CBLAS is installed and add it to `LD_LIBRARY_PATH` .
